### ISSUE TITLE
expected struct `try_future::TryFuture`, found struct `futures::AndThen`

### ISSUE THREAD

**Issue by 0x8f701** [srijs/rust-try-future#2]
![Screenshot from 2019-03-12 04-17-54](https://user-images.githubusercontent.com/33961674/54172281-dc5a0a80-447d-11e9-9c53-3b846db3e3d2.png)

Hello, do you know how to solve this problem?

**Comment by srijs** [comment]
Hi! Can you try to chain `.into_future()` onto the end of your last expression? (E.g. `state.db. (...) .into_future()`)

**Comment by 0x8f701** [comment]
Hello, thanks for your reply, I still get this error.

![Screenshot from 2019-03-12 07-47-21](https://user-images.githubusercontent.com/33961674/54180128-21406a00-449b-11e9-94e2-4041dd734299.png)

**Comment by srijs** [comment]
Ah, my mistake, can you try `into` instead of `into_future`?

**Comment by 0x8f701** [comment]
It works perfectly! Thanks. My last question is how to return early a resolved value.
like in this situation:

![Screenshot from 2019-03-11 12-02-14](https://user-images.githubusercontent.com/33961674/54184431-f2c88c00-44a6-11e9-8928-a7292fcce713.png)

![Screenshot from 2019-03-11 12-07-08](https://user-images.githubusercontent.com/33961674/54184444-f8be6d00-44a6-11e9-8d65-529f2576787c.png)

Do you have any idea? Sorry I am new to rust.

**Comment by 0x8f701** [comment]
Closed, the solution is to replace `impl Future` by `Box<Future>` and package `FutureResult` and `AndThen`, Thank you!
